import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gradient-to-t from-[#212227] via-[#5D3FD3] to-[#212227] relative">
          {children}
          <div className="absolute inset-0 twinkling-stars"></div>
          <div className="absolute inset-0 far-stars"></div>
          <div className="absolute inset-0 close-stars"></div>
          <div className="absolute inset-0 bg-glow"></div>
        </div>
      </body>
    </html>
  );
}
